# This workflow will deploy the built code to Azure Static Web Apps
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy React App
run-name: ${{ github.actor }} is deploying react app

on:
  workflow_run:
    workflows: ["Build React App"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List all artifacts (Debugging Step)
      run: |
        echo "Listing all artifacts:"
        ls -R

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: build
      
    - name: List downloaded artifacts (Debugging Step)
      run: |
        echo "Listing downloaded artifacts:"
        ls -R
    
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"
        output_location: "build"